// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhabbokbhnqioykjimix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoYWJib2tiaG5xaW95a2ppbWl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NDU4MTQsImV4cCI6MjA2NDIyMTgxNH0.2Fo-x0RDwlA1BpEj-Gic3zeRDRL38YJ0PaUpYl6RB5w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);